//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ARCONTROLLER_FEATURE_JumpingSumo_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ARCONTROLLER_FEATURE_JumpingSumo_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ARCONTROLLER_FEATURE_JumpingSumo_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ARCONTROLLER_FEATURE_JumpingSumo_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ARDroneSDK3PINVOKE.delete_ARCONTROLLER_FEATURE_JumpingSumo_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t_int8_t_int8_t__eARCONTROLLER_ERROR sendPilotingPCMD {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendPilotingPCMD_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t_int8_t_int8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendPilotingPCMD_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t_int8_t_int8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t_int8_t_int8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t_int8_t_int8_t__eARCONTROLLER_ERROR setPilotingPCMD {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_setPilotingPCMD_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t_int8_t_int8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_setPilotingPCMD_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t_int8_t_int8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t_int8_t_int8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR setPilotingPCMDFlag {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_setPilotingPCMDFlag_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_setPilotingPCMDFlag_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_int8_t__eARCONTROLLER_ERROR setPilotingPCMDSpeed {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_setPilotingPCMDSpeed_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_int8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_setPilotingPCMDSpeed_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_int8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_int8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_int8_t__eARCONTROLLER_ERROR setPilotingPCMDTurn {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_setPilotingPCMDTurn_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_int8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_setPilotingPCMDTurn_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_int8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_int8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_PILOTING_POSTURE_TYPE__eARCONTROLLER_ERROR sendPilotingPosture {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendPilotingPosture_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_PILOTING_POSTURE_TYPE__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendPilotingPosture_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_PILOTING_POSTURE_TYPE__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_PILOTING_POSTURE_TYPE__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_float__eARCONTROLLER_ERROR sendPilotingAddCapOffset {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendPilotingAddCapOffset_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_float__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendPilotingAddCapOffset_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_float__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_float__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR sendAnimationsJumpStop {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendAnimationsJumpStop_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendAnimationsJumpStop_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR sendAnimationsJumpCancel {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendAnimationsJumpCancel_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendAnimationsJumpCancel_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR sendAnimationsJumpLoad {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendAnimationsJumpLoad_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendAnimationsJumpLoad_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_ANIMATIONS_JUMP_TYPE__eARCONTROLLER_ERROR sendAnimationsJump {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendAnimationsJump_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_ANIMATIONS_JUMP_TYPE__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendAnimationsJump_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_ANIMATIONS_JUMP_TYPE__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_ANIMATIONS_JUMP_TYPE__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_ANIMATIONS_SIMPLEANIMATION_ID__eARCONTROLLER_ERROR sendAnimationsSimpleAnimation {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendAnimationsSimpleAnimation_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_ANIMATIONS_SIMPLEANIMATION_ID__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendAnimationsSimpleAnimation_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_ANIMATIONS_SIMPLEANIMATION_ID__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_ANIMATIONS_SIMPLEANIMATION_ID__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR sendMediaRecordPicture {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendMediaRecordPicture_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendMediaRecordPicture_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_MEDIARECORD_VIDEO_RECORD_uint8_t__eARCONTROLLER_ERROR sendMediaRecordVideo {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendMediaRecordVideo_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_MEDIARECORD_VIDEO_RECORD_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendMediaRecordVideo_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_MEDIARECORD_VIDEO_RECORD_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_MEDIARECORD_VIDEO_RECORD_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR sendMediaRecordPictureV2 {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendMediaRecordPictureV2_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendMediaRecordPictureV2_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_MEDIARECORD_VIDEOV2_RECORD__eARCONTROLLER_ERROR sendMediaRecordVideoV2 {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendMediaRecordVideoV2_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_MEDIARECORD_VIDEOV2_RECORD__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendMediaRecordVideoV2_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_MEDIARECORD_VIDEOV2_RECORD__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_MEDIARECORD_VIDEOV2_RECORD__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_NETWORKSETTINGS_WIFISELECTION_TYPE_eARCOMMANDS_JUMPINGSUMO_NETWORKSETTINGS_WIFISELECTION_BAND_uint8_t__eARCONTROLLER_ERROR sendNetworkSettingsWifiSelection {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendNetworkSettingsWifiSelection_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_NETWORKSETTINGS_WIFISELECTION_TYPE_eARCOMMANDS_JUMPINGSUMO_NETWORKSETTINGS_WIFISELECTION_BAND_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendNetworkSettingsWifiSelection_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_NETWORKSETTINGS_WIFISELECTION_TYPE_eARCOMMANDS_JUMPINGSUMO_NETWORKSETTINGS_WIFISELECTION_BAND_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_NETWORKSETTINGS_WIFISELECTION_TYPE_eARCOMMANDS_JUMPINGSUMO_NETWORKSETTINGS_WIFISELECTION_BAND_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_NETWORK_WIFISCAN_BAND__eARCONTROLLER_ERROR sendNetworkWifiScan {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendNetworkWifiScan_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_NETWORK_WIFISCAN_BAND__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendNetworkWifiScan_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_NETWORK_WIFISCAN_BAND__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_NETWORK_WIFISCAN_BAND__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR sendNetworkWifiAuthChannel {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendNetworkWifiAuthChannel_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendNetworkWifiAuthChannel_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR sendAudioSettingsMasterVolume {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendAudioSettingsMasterVolume_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendAudioSettingsMasterVolume_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_AUDIOSETTINGS_THEME_THEME__eARCONTROLLER_ERROR sendAudioSettingsTheme {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendAudioSettingsTheme_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_AUDIOSETTINGS_THEME_THEME__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendAudioSettingsTheme_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_AUDIOSETTINGS_THEME_THEME__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_eARCOMMANDS_JUMPINGSUMO_AUDIOSETTINGS_THEME_THEME__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR sendRoadPlanAllScriptsMetadata {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendRoadPlanAllScriptsMetadata_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendRoadPlanAllScriptsMetadata_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_p_char_p_char__eARCONTROLLER_ERROR sendRoadPlanScriptUploaded {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendRoadPlanScriptUploaded_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_p_char_p_char__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendRoadPlanScriptUploaded_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_p_char_p_char__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_p_char_p_char__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_p_char__eARCONTROLLER_ERROR sendRoadPlanScriptDelete {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendRoadPlanScriptDelete_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_p_char__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendRoadPlanScriptDelete_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_p_char__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_p_char__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_p_char__eARCONTROLLER_ERROR sendRoadPlanPlayScript {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendRoadPlanPlayScript_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_p_char__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendRoadPlanPlayScript_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_p_char__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_p_char__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR sendSpeedSettingsOutdoor {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendSpeedSettingsOutdoor_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendSpeedSettingsOutdoor_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR sendMediaStreamingVideoEnable {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendMediaStreamingVideoEnable_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_sendMediaStreamingVideoEnable_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_JumpingSumo_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_ARCONTROLLER_FEATURE_JumpingSumo_Private_t privatePart {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_privatePart_set(swigCPtr, SWIGTYPE_p_ARCONTROLLER_FEATURE_JumpingSumo_Private_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_JumpingSumo_t_privatePart_get(swigCPtr);
      SWIGTYPE_p_ARCONTROLLER_FEATURE_JumpingSumo_Private_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ARCONTROLLER_FEATURE_JumpingSumo_Private_t(cPtr, false);
      return ret;
    } 
  }

  public ARCONTROLLER_FEATURE_JumpingSumo_t() : this(ARDroneSDK3PINVOKE.new_ARCONTROLLER_FEATURE_JumpingSumo_t(), true) {
  }

}
