//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ARCONTROLLER_NETWORK_SendingConfiguration_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ARCONTROLLER_NETWORK_SendingConfiguration_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ARCONTROLLER_NETWORK_SendingConfiguration_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ARCONTROLLER_NETWORK_SendingConfiguration_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ARDroneSDK3PINVOKE.delete_ARCONTROLLER_NETWORK_SendingConfiguration_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_eARNETWORK_MANAGER_CALLBACK_RETURN timeoutPolicy {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_NETWORK_SendingConfiguration_t_timeoutPolicy_set(swigCPtr, SWIGTYPE_p_eARNETWORK_MANAGER_CALLBACK_RETURN.getCPtr(value));
      if (ARDroneSDK3PINVOKE.SWIGPendingException.Pending) throw ARDroneSDK3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_eARNETWORK_MANAGER_CALLBACK_RETURN ret = new SWIGTYPE_p_eARNETWORK_MANAGER_CALLBACK_RETURN(ARDroneSDK3PINVOKE.ARCONTROLLER_NETWORK_SendingConfiguration_t_timeoutPolicy_get(swigCPtr), true);
      if (ARDroneSDK3PINVOKE.SWIGPendingException.Pending) throw ARDroneSDK3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public System.IntPtr customData {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_NETWORK_SendingConfiguration_t_customData_set(swigCPtr, new global::System.Runtime.InteropServices.HandleRef(null, value));
    } get{System.IntPtr res = ARDroneSDK3PINVOKE.ARCONTROLLER_NETWORK_SendingConfiguration_t_customData_get(swigCPtr); ; return res;}
  }

  public ARCONTROLLER_NETWORK_SendingConfiguration_t() : this(ARDroneSDK3PINVOKE.new_ARCONTROLLER_NETWORK_SendingConfiguration_t(), true) {
  }

}
