//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ARCONTROLLER_FEATURE_Common_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ARCONTROLLER_FEATURE_Common_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ARCONTROLLER_FEATURE_Common_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ARCONTROLLER_FEATURE_Common_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ARDroneSDK3PINVOKE.delete_ARCONTROLLER_FEATURE_Common_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR sendNetworkDisconnect {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendNetworkDisconnect_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendNetworkDisconnect_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR sendSettingsAllSettings {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendSettingsAllSettings_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendSettingsAllSettings_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR sendSettingsReset {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendSettingsReset_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendSettingsReset_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR sendSettingsProductName {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendSettingsProductName_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendSettingsProductName_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR sendSettingsCountry {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendSettingsCountry_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendSettingsCountry_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_uint8_t__eARCONTROLLER_ERROR sendSettingsAutoCountry {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendSettingsAutoCountry_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendSettingsAutoCountry_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR sendCommonAllStates {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendCommonAllStates_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendCommonAllStates_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR sendCommonCurrentDate {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendCommonCurrentDate_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendCommonCurrentDate_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR sendCommonCurrentTime {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendCommonCurrentTime_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendCommonCurrentTime_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR sendCommonReboot {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendCommonReboot_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendCommonReboot_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR sendOverHeatSwitchOff {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendOverHeatSwitchOff_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendOverHeatSwitchOff_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR sendOverHeatVentilate {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendOverHeatVentilate_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendOverHeatVentilate_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_uint8_t__eARCONTROLLER_ERROR sendWifiSettingsOutdoorSetting {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendWifiSettingsOutdoorSetting_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendWifiSettingsOutdoorSetting_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char_eARCOMMANDS_COMMON_MAVLINK_START_TYPE__eARCONTROLLER_ERROR sendMavlinkStart {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendMavlinkStart_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char_eARCOMMANDS_COMMON_MAVLINK_START_TYPE__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendMavlinkStart_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char_eARCOMMANDS_COMMON_MAVLINK_START_TYPE__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_p_char_eARCOMMANDS_COMMON_MAVLINK_START_TYPE__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR sendMavlinkPause {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendMavlinkPause_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendMavlinkPause_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR sendMavlinkStop {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendMavlinkStop_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendMavlinkStop_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_uint8_t__eARCONTROLLER_ERROR sendCalibrationMagnetoCalibration {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendCalibrationMagnetoCalibration_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendCalibrationMagnetoCalibration_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_double_double__eARCONTROLLER_ERROR sendGPSControllerPositionForRun {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendGPSControllerPositionForRun_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_double_double__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_sendGPSControllerPositionForRun_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_double_double__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_Common_t_double_double__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_ARCONTROLLER_FEATURE_Common_Private_t privatePart {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_privatePart_set(swigCPtr, SWIGTYPE_p_ARCONTROLLER_FEATURE_Common_Private_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_Common_t_privatePart_get(swigCPtr);
      SWIGTYPE_p_ARCONTROLLER_FEATURE_Common_Private_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ARCONTROLLER_FEATURE_Common_Private_t(cPtr, false);
      return ret;
    } 
  }

  public ARCONTROLLER_FEATURE_Common_t() : this(ARDroneSDK3PINVOKE.new_ARCONTROLLER_FEATURE_Common_t(), true) {
  }

}
