//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ARCONTROLLER_FEATURE_ARDrone3_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ARCONTROLLER_FEATURE_ARDrone3_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ARCONTROLLER_FEATURE_ARDrone3_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ARCONTROLLER_FEATURE_ARDrone3_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ARDroneSDK3PINVOKE.delete_ARCONTROLLER_FEATURE_ARDrone3_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR sendPilotingFlatTrim {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingFlatTrim_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingFlatTrim_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR sendPilotingTakeOff {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingTakeOff_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingTakeOff_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_int8_t_int8_t_int8_t_int8_t_float__eARCONTROLLER_ERROR sendPilotingPCMD {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingPCMD_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_int8_t_int8_t_int8_t_int8_t_float__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingPCMD_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_int8_t_int8_t_int8_t_int8_t_float__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_int8_t_int8_t_int8_t_int8_t_float__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_int8_t_int8_t_int8_t_int8_t_float__eARCONTROLLER_ERROR setPilotingPCMD {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_setPilotingPCMD_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_int8_t_int8_t_int8_t_int8_t_float__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_setPilotingPCMD_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_int8_t_int8_t_int8_t_int8_t_float__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_int8_t_int8_t_int8_t_int8_t_float__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR setPilotingPCMDFlag {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_setPilotingPCMDFlag_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_setPilotingPCMDFlag_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR setPilotingPCMDRoll {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_setPilotingPCMDRoll_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_setPilotingPCMDRoll_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR setPilotingPCMDPitch {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_setPilotingPCMDPitch_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_setPilotingPCMDPitch_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR setPilotingPCMDYaw {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_setPilotingPCMDYaw_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_setPilotingPCMDYaw_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR setPilotingPCMDGaz {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_setPilotingPCMDGaz_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_setPilotingPCMDGaz_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR setPilotingPCMDPsi {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_setPilotingPCMDPsi_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_setPilotingPCMDPsi_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR sendPilotingLanding {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingLanding_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingLanding_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR sendPilotingEmergency {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingEmergency_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingEmergency_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR sendPilotingNavigateHome {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingNavigateHome_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingNavigateHome_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR sendPilotingAutoTakeOffMode {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingAutoTakeOffMode_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingAutoTakeOffMode_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION__eARCONTROLLER_ERROR sendAnimationsFlip {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendAnimationsFlip_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendAnimationsFlip_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t_int8_t__eARCONTROLLER_ERROR sendCameraOrientation {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendCameraOrientation_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t_int8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendCameraOrientation_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t_int8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_int8_t_int8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR sendMediaRecordPicture {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendMediaRecordPicture_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendMediaRecordPicture_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEO_RECORD_uint8_t__eARCONTROLLER_ERROR sendMediaRecordVideo {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendMediaRecordVideo_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEO_RECORD_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendMediaRecordVideo_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEO_RECORD_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEO_RECORD_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR sendMediaRecordPictureV2 {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendMediaRecordPictureV2_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendMediaRecordPictureV2_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEOV2_RECORD__eARCONTROLLER_ERROR sendMediaRecordVideoV2 {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendMediaRecordVideoV2_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEOV2_RECORD__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendMediaRecordVideoV2_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEOV2_RECORD__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEOV2_RECORD__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_NETWORK_WIFISCAN_BAND__eARCONTROLLER_ERROR sendNetworkWifiScan {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendNetworkWifiScan_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_NETWORK_WIFISCAN_BAND__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendNetworkWifiScan_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_NETWORK_WIFISCAN_BAND__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_NETWORK_WIFISCAN_BAND__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR sendNetworkWifiAuthChannel {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendNetworkWifiAuthChannel_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendNetworkWifiAuthChannel_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR sendPilotingSettingsMaxAltitude {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingSettingsMaxAltitude_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingSettingsMaxAltitude_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR sendPilotingSettingsMaxTilt {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingSettingsMaxTilt_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingSettingsMaxTilt_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR sendPilotingSettingsAbsolutControl {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingSettingsAbsolutControl_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingSettingsAbsolutControl_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR sendPilotingSettingsMaxDistance {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingSettingsMaxDistance_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingSettingsMaxDistance_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR sendPilotingSettingsNoFlyOverMaxDistance {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingSettingsNoFlyOverMaxDistance_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPilotingSettingsNoFlyOverMaxDistance_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR sendSpeedSettingsMaxVerticalSpeed {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendSpeedSettingsMaxVerticalSpeed_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendSpeedSettingsMaxVerticalSpeed_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR sendSpeedSettingsMaxRotationSpeed {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendSpeedSettingsMaxRotationSpeed_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendSpeedSettingsMaxRotationSpeed_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR sendSpeedSettingsHullProtection {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendSpeedSettingsHullProtection_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendSpeedSettingsHullProtection_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR sendSpeedSettingsOutdoor {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendSpeedSettingsOutdoor_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendSpeedSettingsOutdoor_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_NETWORKSETTINGS_WIFISELECTION_TYPE_eARCOMMANDS_ARDRONE3_NETWORKSETTINGS_WIFISELECTION_BAND_uint8_t__eARCONTROLLER_ERROR sendNetworkSettingsWifiSelection {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendNetworkSettingsWifiSelection_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_NETWORKSETTINGS_WIFISELECTION_TYPE_eARCOMMANDS_ARDRONE3_NETWORKSETTINGS_WIFISELECTION_BAND_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendNetworkSettingsWifiSelection_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_NETWORKSETTINGS_WIFISELECTION_TYPE_eARCOMMANDS_ARDRONE3_NETWORKSETTINGS_WIFISELECTION_BAND_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_NETWORKSETTINGS_WIFISELECTION_TYPE_eARCOMMANDS_ARDRONE3_NETWORKSETTINGS_WIFISELECTION_BAND_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_PICTURESETTINGS_PICTUREFORMATSELECTION_TYPE__eARCONTROLLER_ERROR sendPictureSettingsPictureFormatSelection {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPictureSettingsPictureFormatSelection_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_PICTURESETTINGS_PICTUREFORMATSELECTION_TYPE__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPictureSettingsPictureFormatSelection_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_PICTURESETTINGS_PICTUREFORMATSELECTION_TYPE__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_PICTURESETTINGS_PICTUREFORMATSELECTION_TYPE__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_PICTURESETTINGS_AUTOWHITEBALANCESELECTION_TYPE__eARCONTROLLER_ERROR sendPictureSettingsAutoWhiteBalanceSelection {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPictureSettingsAutoWhiteBalanceSelection_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_PICTURESETTINGS_AUTOWHITEBALANCESELECTION_TYPE__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPictureSettingsAutoWhiteBalanceSelection_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_PICTURESETTINGS_AUTOWHITEBALANCESELECTION_TYPE__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_PICTURESETTINGS_AUTOWHITEBALANCESELECTION_TYPE__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR sendPictureSettingsExpositionSelection {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPictureSettingsExpositionSelection_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPictureSettingsExpositionSelection_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR sendPictureSettingsSaturationSelection {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPictureSettingsSaturationSelection_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPictureSettingsSaturationSelection_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_float__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_float__eARCONTROLLER_ERROR sendPictureSettingsTimelapseSelection {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPictureSettingsTimelapseSelection_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_float__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPictureSettingsTimelapseSelection_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_float__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_float__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_uint8_t__eARCONTROLLER_ERROR sendPictureSettingsVideoAutorecordSelection {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPictureSettingsVideoAutorecordSelection_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendPictureSettingsVideoAutorecordSelection_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR sendMediaStreamingVideoEnable {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendMediaStreamingVideoEnable_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendMediaStreamingVideoEnable_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint8_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_double_double_double__eARCONTROLLER_ERROR sendGPSSettingsSetHome {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendGPSSettingsSetHome_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_double_double_double__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendGPSSettingsSetHome_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_double_double_double__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_double_double_double__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR sendGPSSettingsResetHome {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendGPSSettingsResetHome_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendGPSSettingsResetHome_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_double_double_double_double_double__eARCONTROLLER_ERROR sendGPSSettingsSendControllerGPS {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendGPSSettingsSendControllerGPS_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_double_double_double_double_double__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendGPSSettingsSendControllerGPS_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_double_double_double_double_double__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_double_double_double_double_double__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_GPSSETTINGS_HOMETYPE_TYPE__eARCONTROLLER_ERROR sendGPSSettingsHomeType {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendGPSSettingsHomeType_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_GPSSETTINGS_HOMETYPE_TYPE__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendGPSSettingsHomeType_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_GPSSETTINGS_HOMETYPE_TYPE__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_GPSSETTINGS_HOMETYPE_TYPE__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint16_t__eARCONTROLLER_ERROR sendGPSSettingsReturnHomeDelay {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendGPSSettingsReturnHomeDelay_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint16_t__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendGPSSettingsReturnHomeDelay_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint16_t__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_uint16_t__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_ANTIFLICKERING_ELECTRICFREQUENCY_FREQUENCY__eARCONTROLLER_ERROR sendAntiflickeringElectricFrequency {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendAntiflickeringElectricFrequency_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_ANTIFLICKERING_ELECTRICFREQUENCY_FREQUENCY__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendAntiflickeringElectricFrequency_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_ANTIFLICKERING_ELECTRICFREQUENCY_FREQUENCY__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_ANTIFLICKERING_ELECTRICFREQUENCY_FREQUENCY__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_ANTIFLICKERING_SETMODE_MODE__eARCONTROLLER_ERROR sendAntiflickeringSetMode {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendAntiflickeringSetMode_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_ANTIFLICKERING_SETMODE_MODE__eARCONTROLLER_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_sendAntiflickeringSetMode_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_ANTIFLICKERING_SETMODE_MODE__eARCONTROLLER_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARCONTROLLER_FEATURE_ARDrone3_t_eARCOMMANDS_ARDRONE3_ANTIFLICKERING_SETMODE_MODE__eARCONTROLLER_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_ARCONTROLLER_FEATURE_ARDrone3_Private_t privatePart {
    set {
      ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_privatePart_set(swigCPtr, SWIGTYPE_p_ARCONTROLLER_FEATURE_ARDrone3_Private_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARCONTROLLER_FEATURE_ARDrone3_t_privatePart_get(swigCPtr);
      SWIGTYPE_p_ARCONTROLLER_FEATURE_ARDrone3_Private_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ARCONTROLLER_FEATURE_ARDrone3_Private_t(cPtr, false);
      return ret;
    } 
  }

  public ARCONTROLLER_FEATURE_ARDrone3_t() : this(ARDroneSDK3PINVOKE.new_ARCONTROLLER_FEATURE_ARDrone3_t(), true) {
  }

}
