//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ARDISCOVERY_Device_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ARDISCOVERY_Device_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ARDISCOVERY_Device_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ARDISCOVERY_Device_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ARDroneSDK3PINVOKE.delete_ARDISCOVERY_Device_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string name {
    set {
      ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_name_set(swigCPtr, value);
    } 
    get {
      string ret = ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_name_get(swigCPtr);
      return ret;
    } 
  }

  public eARDISCOVERY_PRODUCT productID {
    set {
      ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_productID_set(swigCPtr, (int)value);
    } 
    get {
      eARDISCOVERY_PRODUCT ret = (eARDISCOVERY_PRODUCT)ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_productID_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_enum_eARDISCOVERY_ERROR_p_eARNETWORKAL_ERROR__p_ARNETWORKAL_Manager_t newNetworkAL {
    set {
      ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_newNetworkAL_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_enum_eARDISCOVERY_ERROR_p_eARNETWORKAL_ERROR__p_ARNETWORKAL_Manager_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_newNetworkAL_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_enum_eARDISCOVERY_ERROR_p_eARNETWORKAL_ERROR__p_ARNETWORKAL_Manager_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_enum_eARDISCOVERY_ERROR_p_eARNETWORKAL_ERROR__p_ARNETWORKAL_Manager_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_p_ARNETWORKAL_Manager_t__eARDISCOVERY_ERROR deleteNetworkAL {
    set {
      ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_deleteNetworkAL_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_p_ARNETWORKAL_Manager_t__eARDISCOVERY_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_deleteNetworkAL_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_p_ARNETWORKAL_Manager_t__eARDISCOVERY_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_p_ARNETWORKAL_Manager_t__eARDISCOVERY_ERROR(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_ARDISCOVERY_NetworkConfiguration_t__eARDISCOVERY_ERROR initNetworkCongifuration {
    set {
      ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_initNetworkCongifuration_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_ARDISCOVERY_NetworkConfiguration_t__eARDISCOVERY_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_initNetworkCongifuration_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_ARDISCOVERY_NetworkConfiguration_t__eARDISCOVERY_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_ARDISCOVERY_NetworkConfiguration_t__eARDISCOVERY_ERROR(cPtr, false);
      return ret;
    } 
  }

  public System.IntPtr specificParameters {
    set {
      ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_specificParameters_set(swigCPtr, new global::System.Runtime.InteropServices.HandleRef(null, value));
    } get{System.IntPtr res = ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_specificParameters_get(swigCPtr); ; return res;}
  }

  public SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_enum_eARDISCOVERY_ERROR__p_void getCopyOfSpecificParameters {
    set {
      ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_getCopyOfSpecificParameters_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_enum_eARDISCOVERY_ERROR__p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_getCopyOfSpecificParameters_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_enum_eARDISCOVERY_ERROR__p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t_p_enum_eARDISCOVERY_ERROR__p_void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t__eARDISCOVERY_ERROR deleteSpecificParameters {
    set {
      ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_deleteSpecificParameters_set(swigCPtr, SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t__eARDISCOVERY_ERROR.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ARDroneSDK3PINVOKE.ARDISCOVERY_Device_t_deleteSpecificParameters_get(swigCPtr);
      SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t__eARDISCOVERY_ERROR ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_ARDISCOVERY_Device_t__eARDISCOVERY_ERROR(cPtr, false);
      return ret;
    } 
  }

  public ARDISCOVERY_Device_t() : this(ARDroneSDK3PINVOKE.new_ARDISCOVERY_Device_t(), true) {
  }

}
