//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum eARCOMMANDS_JUMPINGSUMO_MEDIARECORD_VIDEO_RECORD {
  ARCOMMANDS_JUMPINGSUMO_MEDIARECORD_VIDEO_RECORD_STOP = 0,
  ARCOMMANDS_JUMPINGSUMO_MEDIARECORD_VIDEO_RECORD_START,
  ARCOMMANDS_JUMPINGSUMO_MEDIARECORD_VIDEO_RECORD_MAX
}
