//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum eARCONTROLLER_DEVICE_STATE {
  ARCONTROLLER_DEVICE_STATE_STOPPED = 0,
  ARCONTROLLER_DEVICE_STATE_STARTING,
  ARCONTROLLER_DEVICE_STATE_RUNNING,
  ARCONTROLLER_DEVICE_STATE_PAUSED,
  ARCONTROLLER_DEVICE_STATE_STOPPING,
  ARCONTROLLER_DEVICE_STATE_MAX
}
