//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum eARCOMMANDS_JUMPINGSUMO_PILOTING_POSTURE_TYPE {
  ARCOMMANDS_JUMPINGSUMO_PILOTING_POSTURE_TYPE_STANDING = 0,
  ARCOMMANDS_JUMPINGSUMO_PILOTING_POSTURE_TYPE_JUMPER,
  ARCOMMANDS_JUMPINGSUMO_PILOTING_POSTURE_TYPE_KICKER,
  ARCOMMANDS_JUMPINGSUMO_PILOTING_POSTURE_TYPE_MAX
}
