//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum eARCOMMANDS_MINIDRONE_ANIMATIONS_FLIP_DIRECTION {
  ARCOMMANDS_MINIDRONE_ANIMATIONS_FLIP_DIRECTION_FRONT = 0,
  ARCOMMANDS_MINIDRONE_ANIMATIONS_FLIP_DIRECTION_BACK,
  ARCOMMANDS_MINIDRONE_ANIMATIONS_FLIP_DIRECTION_RIGHT,
  ARCOMMANDS_MINIDRONE_ANIMATIONS_FLIP_DIRECTION_LEFT,
  ARCOMMANDS_MINIDRONE_ANIMATIONS_FLIP_DIRECTION_MAX
}
