//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum eARCOMMANDS_ARDRONE3_NETWORK_WIFISCAN_BAND {
  ARCOMMANDS_ARDRONE3_NETWORK_WIFISCAN_BAND_2_4GHZ = 0,
  ARCOMMANDS_ARDRONE3_NETWORK_WIFISCAN_BAND_5GHZ,
  ARCOMMANDS_ARDRONE3_NETWORK_WIFISCAN_BAND_ALL,
  ARCOMMANDS_ARDRONE3_NETWORK_WIFISCAN_BAND_MAX
}
