//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum eARCONTROLLER_NETWORK_SENDING_DATA_TYPE {
  ARCONTROLLER_NETWORK_SENDING_DATA_TYPE_NOT_ACK = 0,
  ARCONTROLLER_NETWORK_SENDING_DATA_TYPE_ACK,
  ARCONTROLLER_NETWORK_SENDING_DATA_TYPE_HIGH_PRIORITY,
  ARCONTROLLER_NETWORK_SENDING_DATA_TYPE_STREAM,
  ARCONTROLLER_NETWORK_SENDING_DATA_TYPE_MAX
}
