//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum eARDISCOVERY_PRODUCT {
  ARDISCOVERY_PRODUCT_NSNETSERVICE = 0,
  ARDISCOVERY_PRODUCT_ARDRONE = ARDISCOVERY_PRODUCT_NSNETSERVICE,
  ARDISCOVERY_PRODUCT_JS,
  ARDISCOVERY_PRODUCT_SKYCONTROLLER,
  ARDISCOVERY_PRODUCT_BLESERVICE,
  ARDISCOVERY_PRODUCT_MINIDRONE = ARDISCOVERY_PRODUCT_BLESERVICE,
  ARDISCOVERY_PRODUCT_MAX
}
