/*
    Copyright (C) 2014 Parrot SA
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions
    are met:
    * Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in
    the documentation and/or other materials provided with the
    distribution.
    * Neither the name of Parrot nor the names
    of its contributors may be used to endorse or promote products
    derived from this software without specific prior written
    permission.
    
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
    OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
    AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
    OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
    OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
    SUCH DAMAGE.
*/
/********************************************
 *            AUTOGENERATED FILE            *
 *             DO NOT MODIFY IT             *
 *                                          *
 * To add new commands :                    *
 *  - Modify ../Xml/commands.xml file       *
 *  - Re-run generateCommandsList.py script *
 *                                          *
 ********************************************/
#include <config.h>
#include <stdlib.h>
#include "Sources/ARCOMMANDS_ReadWrite.h"
#include "Includes/libARCommands/ARCOMMANDS_Types.h"
#include "Includes/libARCommands/ARCOMMANDS_Filter.h"
#include "Sources/ARCOMMANDS_Ids.h"


// ARCOMMANDS_Filter_t structure definition
struct ARCOMMANDS_Filter_t
{
    // Project common
    // Class Network
    eARCOMMANDS_FILTER_STATUS CmdCommonNetworkDisconnectBehavior;
    // Class NetworkEvent
    eARCOMMANDS_FILTER_STATUS CmdCommonNetworkEventDisconnectionBehavior;
    // Class Settings
    eARCOMMANDS_FILTER_STATUS CmdCommonSettingsAllSettingsBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonSettingsResetBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonSettingsProductNameBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonSettingsCountryBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonSettingsAutoCountryBehavior;
    // Class SettingsState
    eARCOMMANDS_FILTER_STATUS CmdCommonSettingsStateAllSettingsChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonSettingsStateResetChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonSettingsStateProductNameChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonSettingsStateProductVersionChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonSettingsStateProductSerialHighChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonSettingsStateProductSerialLowChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonSettingsStateCountryChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonSettingsStateAutoCountryChangedBehavior;
    // Class Common
    eARCOMMANDS_FILTER_STATUS CmdCommonCommonAllStatesBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonCommonCurrentDateBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonCommonCurrentTimeBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonCommonRebootBehavior;
    // Class CommonState
    eARCOMMANDS_FILTER_STATUS CmdCommonCommonStateAllStatesChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonCommonStateBatteryStateChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonCommonStateMassStorageStateListChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonCommonStateMassStorageInfoStateListChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonCommonStateCurrentDateChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonCommonStateCurrentTimeChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonCommonStateMassStorageInfoRemainingListChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonCommonStateWifiSignalChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonCommonStateSensorsStatesListChangedBehavior;
    // Class OverHeat
    eARCOMMANDS_FILTER_STATUS CmdCommonOverHeatSwitchOffBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonOverHeatVentilateBehavior;
    // Class OverHeatState
    eARCOMMANDS_FILTER_STATUS CmdCommonOverHeatStateOverHeatChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonOverHeatStateOverHeatRegulationChangedBehavior;
    // Class ControllerState
    eARCOMMANDS_FILTER_STATUS CmdCommonControllerStateIsPilotingChangedBehavior;
    // Class WifiSettings
    eARCOMMANDS_FILTER_STATUS CmdCommonWifiSettingsOutdoorSettingBehavior;
    // Class WifiSettingsState
    eARCOMMANDS_FILTER_STATUS CmdCommonWifiSettingsStateOutdoorSettingsChangedBehavior;
    // Class Mavlink
    eARCOMMANDS_FILTER_STATUS CmdCommonMavlinkStartBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonMavlinkPauseBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonMavlinkStopBehavior;
    // Class MavlinkState
    eARCOMMANDS_FILTER_STATUS CmdCommonMavlinkStateMavlinkFilePlayingStateChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonMavlinkStateMavlinkPlayErrorStateChangedBehavior;
    // Class Calibration
    eARCOMMANDS_FILTER_STATUS CmdCommonCalibrationMagnetoCalibrationBehavior;
    // Class CalibrationState
    eARCOMMANDS_FILTER_STATUS CmdCommonCalibrationStateMagnetoCalibrationStateChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonCalibrationStateMagnetoCalibrationRequiredStateBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonCalibrationStateMagnetoCalibrationAxisToCalibrateChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonCalibrationStateMagnetoCalibrationStartedChangedBehavior;
    // Class CameraSettingsState
    eARCOMMANDS_FILTER_STATUS CmdCommonCameraSettingsStateCameraSettingsChangedBehavior;
    // Class GPS
    eARCOMMANDS_FILTER_STATUS CmdCommonGPSControllerPositionForRunBehavior;
    // Class FlightPlanState
    eARCOMMANDS_FILTER_STATUS CmdCommonFlightPlanStateAvailabilityStateChangedBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonFlightPlanStateComponentStateListChangedBehavior;
    // Class FlightPlanEvent
    eARCOMMANDS_FILTER_STATUS CmdCommonFlightPlanEventStartingErrorEventBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonFlightPlanEventSpeedBridleEventBehavior;
    // Class ARLibsVersionsState
    eARCOMMANDS_FILTER_STATUS CmdCommonARLibsVersionsStateControllerLibARCommandsVersionBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonARLibsVersionsStateSkyControllerLibARCommandsVersionBehavior;
    eARCOMMANDS_FILTER_STATUS CmdCommonARLibsVersionsStateDeviceLibARCommandsVersionBehavior;

};


// Constructor
ARCOMMANDS_Filter_t* ARCOMMANDS_Filter_NewFilter (eARCOMMANDS_FILTER_STATUS defaultBehavior, eARCOMMANDS_FILTER_ERROR *error)
{
    ARCOMMANDS_Filter_t *retFilter = NULL;
    eARCOMMANDS_FILTER_ERROR localError = ARCOMMANDS_FILTER_OK;
    if ((defaultBehavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (defaultBehavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        localError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Args check

    if (localError == ARCOMMANDS_FILTER_OK)
    {
        retFilter = malloc (sizeof (struct ARCOMMANDS_Filter_t));
        if (retFilter == NULL)
        {
            localError = ARCOMMANDS_FILTER_ERROR_ALLOC;
        } // No else : Error processing.
    } // No else : Processing block

    // Setup default behavior
    if (localError == ARCOMMANDS_FILTER_OK)
    {
        // Projects common
        // Class Network
        retFilter->CmdCommonNetworkDisconnectBehavior = defaultBehavior;
        // Class NetworkEvent
        retFilter->CmdCommonNetworkEventDisconnectionBehavior = defaultBehavior;
        // Class Settings
        retFilter->CmdCommonSettingsAllSettingsBehavior = defaultBehavior;
        retFilter->CmdCommonSettingsResetBehavior = defaultBehavior;
        retFilter->CmdCommonSettingsProductNameBehavior = defaultBehavior;
        retFilter->CmdCommonSettingsCountryBehavior = defaultBehavior;
        retFilter->CmdCommonSettingsAutoCountryBehavior = defaultBehavior;
        // Class SettingsState
        retFilter->CmdCommonSettingsStateAllSettingsChangedBehavior = defaultBehavior;
        retFilter->CmdCommonSettingsStateResetChangedBehavior = defaultBehavior;
        retFilter->CmdCommonSettingsStateProductNameChangedBehavior = defaultBehavior;
        retFilter->CmdCommonSettingsStateProductVersionChangedBehavior = defaultBehavior;
        retFilter->CmdCommonSettingsStateProductSerialHighChangedBehavior = defaultBehavior;
        retFilter->CmdCommonSettingsStateProductSerialLowChangedBehavior = defaultBehavior;
        retFilter->CmdCommonSettingsStateCountryChangedBehavior = defaultBehavior;
        retFilter->CmdCommonSettingsStateAutoCountryChangedBehavior = defaultBehavior;
        // Class Common
        retFilter->CmdCommonCommonAllStatesBehavior = defaultBehavior;
        retFilter->CmdCommonCommonCurrentDateBehavior = defaultBehavior;
        retFilter->CmdCommonCommonCurrentTimeBehavior = defaultBehavior;
        retFilter->CmdCommonCommonRebootBehavior = defaultBehavior;
        // Class CommonState
        retFilter->CmdCommonCommonStateAllStatesChangedBehavior = defaultBehavior;
        retFilter->CmdCommonCommonStateBatteryStateChangedBehavior = defaultBehavior;
        retFilter->CmdCommonCommonStateMassStorageStateListChangedBehavior = defaultBehavior;
        retFilter->CmdCommonCommonStateMassStorageInfoStateListChangedBehavior = defaultBehavior;
        retFilter->CmdCommonCommonStateCurrentDateChangedBehavior = defaultBehavior;
        retFilter->CmdCommonCommonStateCurrentTimeChangedBehavior = defaultBehavior;
        retFilter->CmdCommonCommonStateMassStorageInfoRemainingListChangedBehavior = defaultBehavior;
        retFilter->CmdCommonCommonStateWifiSignalChangedBehavior = defaultBehavior;
        retFilter->CmdCommonCommonStateSensorsStatesListChangedBehavior = defaultBehavior;
        // Class OverHeat
        retFilter->CmdCommonOverHeatSwitchOffBehavior = defaultBehavior;
        retFilter->CmdCommonOverHeatVentilateBehavior = defaultBehavior;
        // Class OverHeatState
        retFilter->CmdCommonOverHeatStateOverHeatChangedBehavior = defaultBehavior;
        retFilter->CmdCommonOverHeatStateOverHeatRegulationChangedBehavior = defaultBehavior;
        // Class ControllerState
        retFilter->CmdCommonControllerStateIsPilotingChangedBehavior = defaultBehavior;
        // Class WifiSettings
        retFilter->CmdCommonWifiSettingsOutdoorSettingBehavior = defaultBehavior;
        // Class WifiSettingsState
        retFilter->CmdCommonWifiSettingsStateOutdoorSettingsChangedBehavior = defaultBehavior;
        // Class Mavlink
        retFilter->CmdCommonMavlinkStartBehavior = defaultBehavior;
        retFilter->CmdCommonMavlinkPauseBehavior = defaultBehavior;
        retFilter->CmdCommonMavlinkStopBehavior = defaultBehavior;
        // Class MavlinkState
        retFilter->CmdCommonMavlinkStateMavlinkFilePlayingStateChangedBehavior = defaultBehavior;
        retFilter->CmdCommonMavlinkStateMavlinkPlayErrorStateChangedBehavior = defaultBehavior;
        // Class Calibration
        retFilter->CmdCommonCalibrationMagnetoCalibrationBehavior = defaultBehavior;
        // Class CalibrationState
        retFilter->CmdCommonCalibrationStateMagnetoCalibrationStateChangedBehavior = defaultBehavior;
        retFilter->CmdCommonCalibrationStateMagnetoCalibrationRequiredStateBehavior = defaultBehavior;
        retFilter->CmdCommonCalibrationStateMagnetoCalibrationAxisToCalibrateChangedBehavior = defaultBehavior;
        retFilter->CmdCommonCalibrationStateMagnetoCalibrationStartedChangedBehavior = defaultBehavior;
        // Class CameraSettingsState
        retFilter->CmdCommonCameraSettingsStateCameraSettingsChangedBehavior = defaultBehavior;
        // Class GPS
        retFilter->CmdCommonGPSControllerPositionForRunBehavior = defaultBehavior;
        // Class FlightPlanState
        retFilter->CmdCommonFlightPlanStateAvailabilityStateChangedBehavior = defaultBehavior;
        retFilter->CmdCommonFlightPlanStateComponentStateListChangedBehavior = defaultBehavior;
        // Class FlightPlanEvent
        retFilter->CmdCommonFlightPlanEventStartingErrorEventBehavior = defaultBehavior;
        retFilter->CmdCommonFlightPlanEventSpeedBridleEventBehavior = defaultBehavior;
        // Class ARLibsVersionsState
        retFilter->CmdCommonARLibsVersionsStateControllerLibARCommandsVersionBehavior = defaultBehavior;
        retFilter->CmdCommonARLibsVersionsStateSkyControllerLibARCommandsVersionBehavior = defaultBehavior;
        retFilter->CmdCommonARLibsVersionsStateDeviceLibARCommandsVersionBehavior = defaultBehavior;
    } // No else : Processing block

    if (localError != ARCOMMANDS_FILTER_OK)
    {
        if (retFilter != NULL)
        {
            ARCOMMANDS_Filter_DeleteFilter (&retFilter);
        } // No else : Nothing to do if the pointer is already NULL
    } // No else : Only do cleanup if an error occured

    if (error != NULL)
    {
        *error = localError;
    } // No else : Set error only if pointer is not NULL
    return retFilter;
}

void ARCOMMANDS_Filter_DeleteFilter (ARCOMMANDS_Filter_t **filter)
{
    if ((filter != NULL) &&
        (*filter != NULL))
    {
        free (*filter);
        *filter = NULL;
    } // No else : No need to delete an invalid filter instance
}

eARCOMMANDS_FILTER_STATUS ARCOMMANDS_Filter_FilterCommand (ARCOMMANDS_Filter_t *filter, uint8_t *buffer, uint32_t len, eARCOMMANDS_FILTER_ERROR *error)
{
    eARCOMMANDS_ID_PROJECT commandProject = -1;
    int commandClass = -1;
    int commandId = -1;
    int32_t offset = 0;
    int32_t readError = 0;
    eARCOMMANDS_FILTER_ERROR localError = ARCOMMANDS_FILTER_OK;
    eARCOMMANDS_FILTER_STATUS retStatus = ARCOMMANDS_FILTER_STATUS_UNKNOWN;

    // Args check
    if (filter == NULL)
    {
        localError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((buffer == NULL) ||
        (len < 4))
    {
        localError = ARCOMMANDS_FILTER_ERROR_BAD_BUFFER;
    } // No else : Args check

    if (localError == ARCOMMANDS_FILTER_OK)
    {
        commandProject = ARCOMMANDS_ReadWrite_Read8FromBuffer (buffer, len, &offset, &readError);
        if (readError == 1)
        {
            localError = ARCOMMANDS_FILTER_ERROR_BAD_BUFFER;
        }
    } // No else : Processing block

    if (localError == ARCOMMANDS_FILTER_OK)
    {
        commandClass = ARCOMMANDS_ReadWrite_Read8FromBuffer (buffer, len, &offset, &readError);
        if (readError == 1)
        {
            localError = ARCOMMANDS_FILTER_ERROR_BAD_BUFFER;
        }
    } // No else : Processing block

    if (localError == ARCOMMANDS_FILTER_OK)
    {
        commandId = ARCOMMANDS_ReadWrite_Read16FromBuffer (buffer, len, &offset, &readError);
        if (readError == 1)
        {
            localError = ARCOMMANDS_FILTER_ERROR_BAD_BUFFER;
        }
    } // No else : Processing block

    if (localError == ARCOMMANDS_FILTER_OK)
    {
        switch (commandProject)
        {
        case ARCOMMANDS_ID_PROJECT_COMMON:
        {
            switch (commandClass)
            {
            case ARCOMMANDS_ID_COMMON_CLASS_NETWORK:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_NETWORK_CMD_DISCONNECT:
                {
                    retStatus = filter->CmdCommonNetworkDisconnectBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_NETWORK_CMD_DISCONNECT */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_NETWORK */
            case ARCOMMANDS_ID_COMMON_CLASS_NETWORKEVENT:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_NETWORKEVENT_CMD_DISCONNECTION:
                {
                    retStatus = filter->CmdCommonNetworkEventDisconnectionBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_NETWORKEVENT_CMD_DISCONNECTION */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_NETWORKEVENT */
            case ARCOMMANDS_ID_COMMON_CLASS_SETTINGS:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_SETTINGS_CMD_ALLSETTINGS:
                {
                    retStatus = filter->CmdCommonSettingsAllSettingsBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_SETTINGS_CMD_ALLSETTINGS */
                case ARCOMMANDS_ID_COMMON_SETTINGS_CMD_RESET:
                {
                    retStatus = filter->CmdCommonSettingsResetBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_SETTINGS_CMD_RESET */
                case ARCOMMANDS_ID_COMMON_SETTINGS_CMD_PRODUCTNAME:
                {
                    retStatus = filter->CmdCommonSettingsProductNameBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_SETTINGS_CMD_PRODUCTNAME */
                case ARCOMMANDS_ID_COMMON_SETTINGS_CMD_COUNTRY:
                {
                    retStatus = filter->CmdCommonSettingsCountryBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_SETTINGS_CMD_COUNTRY */
                case ARCOMMANDS_ID_COMMON_SETTINGS_CMD_AUTOCOUNTRY:
                {
                    retStatus = filter->CmdCommonSettingsAutoCountryBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_SETTINGS_CMD_AUTOCOUNTRY */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_SETTINGS */
            case ARCOMMANDS_ID_COMMON_CLASS_SETTINGSSTATE:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_ALLSETTINGSCHANGED:
                {
                    retStatus = filter->CmdCommonSettingsStateAllSettingsChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_ALLSETTINGSCHANGED */
                case ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_RESETCHANGED:
                {
                    retStatus = filter->CmdCommonSettingsStateResetChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_RESETCHANGED */
                case ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_PRODUCTNAMECHANGED:
                {
                    retStatus = filter->CmdCommonSettingsStateProductNameChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_PRODUCTNAMECHANGED */
                case ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_PRODUCTVERSIONCHANGED:
                {
                    retStatus = filter->CmdCommonSettingsStateProductVersionChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_PRODUCTVERSIONCHANGED */
                case ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_PRODUCTSERIALHIGHCHANGED:
                {
                    retStatus = filter->CmdCommonSettingsStateProductSerialHighChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_PRODUCTSERIALHIGHCHANGED */
                case ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_PRODUCTSERIALLOWCHANGED:
                {
                    retStatus = filter->CmdCommonSettingsStateProductSerialLowChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_PRODUCTSERIALLOWCHANGED */
                case ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_COUNTRYCHANGED:
                {
                    retStatus = filter->CmdCommonSettingsStateCountryChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_COUNTRYCHANGED */
                case ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_AUTOCOUNTRYCHANGED:
                {
                    retStatus = filter->CmdCommonSettingsStateAutoCountryChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_SETTINGSSTATE_CMD_AUTOCOUNTRYCHANGED */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_SETTINGSSTATE */
            case ARCOMMANDS_ID_COMMON_CLASS_COMMON:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_COMMON_CMD_ALLSTATES:
                {
                    retStatus = filter->CmdCommonCommonAllStatesBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_COMMON_CMD_ALLSTATES */
                case ARCOMMANDS_ID_COMMON_COMMON_CMD_CURRENTDATE:
                {
                    retStatus = filter->CmdCommonCommonCurrentDateBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_COMMON_CMD_CURRENTDATE */
                case ARCOMMANDS_ID_COMMON_COMMON_CMD_CURRENTTIME:
                {
                    retStatus = filter->CmdCommonCommonCurrentTimeBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_COMMON_CMD_CURRENTTIME */
                case ARCOMMANDS_ID_COMMON_COMMON_CMD_REBOOT:
                {
                    retStatus = filter->CmdCommonCommonRebootBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_COMMON_CMD_REBOOT */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_COMMON */
            case ARCOMMANDS_ID_COMMON_CLASS_COMMONSTATE:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_ALLSTATESCHANGED:
                {
                    retStatus = filter->CmdCommonCommonStateAllStatesChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_ALLSTATESCHANGED */
                case ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_BATTERYSTATECHANGED:
                {
                    retStatus = filter->CmdCommonCommonStateBatteryStateChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_BATTERYSTATECHANGED */
                case ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_MASSSTORAGESTATELISTCHANGED:
                {
                    retStatus = filter->CmdCommonCommonStateMassStorageStateListChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_MASSSTORAGESTATELISTCHANGED */
                case ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_MASSSTORAGEINFOSTATELISTCHANGED:
                {
                    retStatus = filter->CmdCommonCommonStateMassStorageInfoStateListChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_MASSSTORAGEINFOSTATELISTCHANGED */
                case ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_CURRENTDATECHANGED:
                {
                    retStatus = filter->CmdCommonCommonStateCurrentDateChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_CURRENTDATECHANGED */
                case ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_CURRENTTIMECHANGED:
                {
                    retStatus = filter->CmdCommonCommonStateCurrentTimeChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_CURRENTTIMECHANGED */
                case ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_MASSSTORAGEINFOREMAININGLISTCHANGED:
                {
                    retStatus = filter->CmdCommonCommonStateMassStorageInfoRemainingListChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_MASSSTORAGEINFOREMAININGLISTCHANGED */
                case ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_WIFISIGNALCHANGED:
                {
                    retStatus = filter->CmdCommonCommonStateWifiSignalChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_WIFISIGNALCHANGED */
                case ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_SENSORSSTATESLISTCHANGED:
                {
                    retStatus = filter->CmdCommonCommonStateSensorsStatesListChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_SENSORSSTATESLISTCHANGED */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_COMMONSTATE */
            case ARCOMMANDS_ID_COMMON_CLASS_OVERHEAT:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_OVERHEAT_CMD_SWITCHOFF:
                {
                    retStatus = filter->CmdCommonOverHeatSwitchOffBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_OVERHEAT_CMD_SWITCHOFF */
                case ARCOMMANDS_ID_COMMON_OVERHEAT_CMD_VENTILATE:
                {
                    retStatus = filter->CmdCommonOverHeatVentilateBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_OVERHEAT_CMD_VENTILATE */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_OVERHEAT */
            case ARCOMMANDS_ID_COMMON_CLASS_OVERHEATSTATE:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_OVERHEATSTATE_CMD_OVERHEATCHANGED:
                {
                    retStatus = filter->CmdCommonOverHeatStateOverHeatChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_OVERHEATSTATE_CMD_OVERHEATCHANGED */
                case ARCOMMANDS_ID_COMMON_OVERHEATSTATE_CMD_OVERHEATREGULATIONCHANGED:
                {
                    retStatus = filter->CmdCommonOverHeatStateOverHeatRegulationChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_OVERHEATSTATE_CMD_OVERHEATREGULATIONCHANGED */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_OVERHEATSTATE */
            case ARCOMMANDS_ID_COMMON_CLASS_CONTROLLERSTATE:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_CONTROLLERSTATE_CMD_ISPILOTINGCHANGED:
                {
                    retStatus = filter->CmdCommonControllerStateIsPilotingChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_CONTROLLERSTATE_CMD_ISPILOTINGCHANGED */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_CONTROLLERSTATE */
            case ARCOMMANDS_ID_COMMON_CLASS_WIFISETTINGS:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_WIFISETTINGS_CMD_OUTDOORSETTING:
                {
                    retStatus = filter->CmdCommonWifiSettingsOutdoorSettingBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_WIFISETTINGS_CMD_OUTDOORSETTING */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_WIFISETTINGS */
            case ARCOMMANDS_ID_COMMON_CLASS_WIFISETTINGSSTATE:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_WIFISETTINGSSTATE_CMD_OUTDOORSETTINGSCHANGED:
                {
                    retStatus = filter->CmdCommonWifiSettingsStateOutdoorSettingsChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_WIFISETTINGSSTATE_CMD_OUTDOORSETTINGSCHANGED */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_WIFISETTINGSSTATE */
            case ARCOMMANDS_ID_COMMON_CLASS_MAVLINK:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_MAVLINK_CMD_START:
                {
                    retStatus = filter->CmdCommonMavlinkStartBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_MAVLINK_CMD_START */
                case ARCOMMANDS_ID_COMMON_MAVLINK_CMD_PAUSE:
                {
                    retStatus = filter->CmdCommonMavlinkPauseBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_MAVLINK_CMD_PAUSE */
                case ARCOMMANDS_ID_COMMON_MAVLINK_CMD_STOP:
                {
                    retStatus = filter->CmdCommonMavlinkStopBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_MAVLINK_CMD_STOP */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_MAVLINK */
            case ARCOMMANDS_ID_COMMON_CLASS_MAVLINKSTATE:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_MAVLINKSTATE_CMD_MAVLINKFILEPLAYINGSTATECHANGED:
                {
                    retStatus = filter->CmdCommonMavlinkStateMavlinkFilePlayingStateChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_MAVLINKSTATE_CMD_MAVLINKFILEPLAYINGSTATECHANGED */
                case ARCOMMANDS_ID_COMMON_MAVLINKSTATE_CMD_MAVLINKPLAYERRORSTATECHANGED:
                {
                    retStatus = filter->CmdCommonMavlinkStateMavlinkPlayErrorStateChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_MAVLINKSTATE_CMD_MAVLINKPLAYERRORSTATECHANGED */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_MAVLINKSTATE */
            case ARCOMMANDS_ID_COMMON_CLASS_CALIBRATION:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_CALIBRATION_CMD_MAGNETOCALIBRATION:
                {
                    retStatus = filter->CmdCommonCalibrationMagnetoCalibrationBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_CALIBRATION_CMD_MAGNETOCALIBRATION */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_CALIBRATION */
            case ARCOMMANDS_ID_COMMON_CLASS_CALIBRATIONSTATE:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_CALIBRATIONSTATE_CMD_MAGNETOCALIBRATIONSTATECHANGED:
                {
                    retStatus = filter->CmdCommonCalibrationStateMagnetoCalibrationStateChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_CALIBRATIONSTATE_CMD_MAGNETOCALIBRATIONSTATECHANGED */
                case ARCOMMANDS_ID_COMMON_CALIBRATIONSTATE_CMD_MAGNETOCALIBRATIONREQUIREDSTATE:
                {
                    retStatus = filter->CmdCommonCalibrationStateMagnetoCalibrationRequiredStateBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_CALIBRATIONSTATE_CMD_MAGNETOCALIBRATIONREQUIREDSTATE */
                case ARCOMMANDS_ID_COMMON_CALIBRATIONSTATE_CMD_MAGNETOCALIBRATIONAXISTOCALIBRATECHANGED:
                {
                    retStatus = filter->CmdCommonCalibrationStateMagnetoCalibrationAxisToCalibrateChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_CALIBRATIONSTATE_CMD_MAGNETOCALIBRATIONAXISTOCALIBRATECHANGED */
                case ARCOMMANDS_ID_COMMON_CALIBRATIONSTATE_CMD_MAGNETOCALIBRATIONSTARTEDCHANGED:
                {
                    retStatus = filter->CmdCommonCalibrationStateMagnetoCalibrationStartedChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_CALIBRATIONSTATE_CMD_MAGNETOCALIBRATIONSTARTEDCHANGED */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_CALIBRATIONSTATE */
            case ARCOMMANDS_ID_COMMON_CLASS_CAMERASETTINGSSTATE:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_CAMERASETTINGSSTATE_CMD_CAMERASETTINGSCHANGED:
                {
                    retStatus = filter->CmdCommonCameraSettingsStateCameraSettingsChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_CAMERASETTINGSSTATE_CMD_CAMERASETTINGSCHANGED */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_CAMERASETTINGSSTATE */
            case ARCOMMANDS_ID_COMMON_CLASS_GPS:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_GPS_CMD_CONTROLLERPOSITIONFORRUN:
                {
                    retStatus = filter->CmdCommonGPSControllerPositionForRunBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_GPS_CMD_CONTROLLERPOSITIONFORRUN */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_GPS */
            case ARCOMMANDS_ID_COMMON_CLASS_FLIGHTPLANSTATE:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_FLIGHTPLANSTATE_CMD_AVAILABILITYSTATECHANGED:
                {
                    retStatus = filter->CmdCommonFlightPlanStateAvailabilityStateChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_FLIGHTPLANSTATE_CMD_AVAILABILITYSTATECHANGED */
                case ARCOMMANDS_ID_COMMON_FLIGHTPLANSTATE_CMD_COMPONENTSTATELISTCHANGED:
                {
                    retStatus = filter->CmdCommonFlightPlanStateComponentStateListChangedBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_FLIGHTPLANSTATE_CMD_COMPONENTSTATELISTCHANGED */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_FLIGHTPLANSTATE */
            case ARCOMMANDS_ID_COMMON_CLASS_FLIGHTPLANEVENT:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_FLIGHTPLANEVENT_CMD_STARTINGERROREVENT:
                {
                    retStatus = filter->CmdCommonFlightPlanEventStartingErrorEventBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_FLIGHTPLANEVENT_CMD_STARTINGERROREVENT */
                case ARCOMMANDS_ID_COMMON_FLIGHTPLANEVENT_CMD_SPEEDBRIDLEEVENT:
                {
                    retStatus = filter->CmdCommonFlightPlanEventSpeedBridleEventBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_FLIGHTPLANEVENT_CMD_SPEEDBRIDLEEVENT */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_FLIGHTPLANEVENT */
            case ARCOMMANDS_ID_COMMON_CLASS_ARLIBSVERSIONSSTATE:
            {
                switch (commandId)
                {
                case ARCOMMANDS_ID_COMMON_ARLIBSVERSIONSSTATE_CMD_CONTROLLERLIBARCOMMANDSVERSION:
                {
                    retStatus = filter->CmdCommonARLibsVersionsStateControllerLibARCommandsVersionBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_ARLIBSVERSIONSSTATE_CMD_CONTROLLERLIBARCOMMANDSVERSION */
                case ARCOMMANDS_ID_COMMON_ARLIBSVERSIONSSTATE_CMD_SKYCONTROLLERLIBARCOMMANDSVERSION:
                {
                    retStatus = filter->CmdCommonARLibsVersionsStateSkyControllerLibARCommandsVersionBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_ARLIBSVERSIONSSTATE_CMD_SKYCONTROLLERLIBARCOMMANDSVERSION */
                case ARCOMMANDS_ID_COMMON_ARLIBSVERSIONSSTATE_CMD_DEVICELIBARCOMMANDSVERSION:
                {
                    retStatus = filter->CmdCommonARLibsVersionsStateDeviceLibARCommandsVersionBehavior;
                }
                break; /* ARCOMMANDS_ID_COMMON_ARLIBSVERSIONSSTATE_CMD_DEVICELIBARCOMMANDSVERSION */
                default:
                    // Do nothing, the default answer is already UNKNOWN
                    break;
                }
            }
            break; /* ARCOMMANDS_ID_COMMON_CLASS_ARLIBSVERSIONSSTATE */
            default:
                // Do nothing, the default answer is already UNKNOWN
                break;
            }
        }
        break; /* ARCOMMANDS_ID_PROJECT_COMMON */
        default:
            // Do nothing, the default answer is already UNKNOWN
            break;
        }
    }

    if (localError != ARCOMMANDS_FILTER_OK)
    {
        retStatus = ARCOMMANDS_FILTER_STATUS_ERROR;
    } // No else : Keep retStatus if no error occured

    if (error != NULL)
    {
        *error = localError;
    } // No else : Set error only if pointer is not NULL

    return retStatus;
}


// Filter ON/OFF functions
// Project common

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonNetworkDisconnectBehavior = behavior;
        filter->CmdCommonNetworkEventDisconnectionBehavior = behavior;
        filter->CmdCommonSettingsAllSettingsBehavior = behavior;
        filter->CmdCommonSettingsResetBehavior = behavior;
        filter->CmdCommonSettingsProductNameBehavior = behavior;
        filter->CmdCommonSettingsCountryBehavior = behavior;
        filter->CmdCommonSettingsAutoCountryBehavior = behavior;
        filter->CmdCommonSettingsStateAllSettingsChangedBehavior = behavior;
        filter->CmdCommonSettingsStateResetChangedBehavior = behavior;
        filter->CmdCommonSettingsStateProductNameChangedBehavior = behavior;
        filter->CmdCommonSettingsStateProductVersionChangedBehavior = behavior;
        filter->CmdCommonSettingsStateProductSerialHighChangedBehavior = behavior;
        filter->CmdCommonSettingsStateProductSerialLowChangedBehavior = behavior;
        filter->CmdCommonSettingsStateCountryChangedBehavior = behavior;
        filter->CmdCommonSettingsStateAutoCountryChangedBehavior = behavior;
        filter->CmdCommonCommonAllStatesBehavior = behavior;
        filter->CmdCommonCommonCurrentDateBehavior = behavior;
        filter->CmdCommonCommonCurrentTimeBehavior = behavior;
        filter->CmdCommonCommonRebootBehavior = behavior;
        filter->CmdCommonCommonStateAllStatesChangedBehavior = behavior;
        filter->CmdCommonCommonStateBatteryStateChangedBehavior = behavior;
        filter->CmdCommonCommonStateMassStorageStateListChangedBehavior = behavior;
        filter->CmdCommonCommonStateMassStorageInfoStateListChangedBehavior = behavior;
        filter->CmdCommonCommonStateCurrentDateChangedBehavior = behavior;
        filter->CmdCommonCommonStateCurrentTimeChangedBehavior = behavior;
        filter->CmdCommonCommonStateMassStorageInfoRemainingListChangedBehavior = behavior;
        filter->CmdCommonCommonStateWifiSignalChangedBehavior = behavior;
        filter->CmdCommonCommonStateSensorsStatesListChangedBehavior = behavior;
        filter->CmdCommonOverHeatSwitchOffBehavior = behavior;
        filter->CmdCommonOverHeatVentilateBehavior = behavior;
        filter->CmdCommonOverHeatStateOverHeatChangedBehavior = behavior;
        filter->CmdCommonOverHeatStateOverHeatRegulationChangedBehavior = behavior;
        filter->CmdCommonControllerStateIsPilotingChangedBehavior = behavior;
        filter->CmdCommonWifiSettingsOutdoorSettingBehavior = behavior;
        filter->CmdCommonWifiSettingsStateOutdoorSettingsChangedBehavior = behavior;
        filter->CmdCommonMavlinkStartBehavior = behavior;
        filter->CmdCommonMavlinkPauseBehavior = behavior;
        filter->CmdCommonMavlinkStopBehavior = behavior;
        filter->CmdCommonMavlinkStateMavlinkFilePlayingStateChangedBehavior = behavior;
        filter->CmdCommonMavlinkStateMavlinkPlayErrorStateChangedBehavior = behavior;
        filter->CmdCommonCalibrationMagnetoCalibrationBehavior = behavior;
        filter->CmdCommonCalibrationStateMagnetoCalibrationStateChangedBehavior = behavior;
        filter->CmdCommonCalibrationStateMagnetoCalibrationRequiredStateBehavior = behavior;
        filter->CmdCommonCalibrationStateMagnetoCalibrationAxisToCalibrateChangedBehavior = behavior;
        filter->CmdCommonCalibrationStateMagnetoCalibrationStartedChangedBehavior = behavior;
        filter->CmdCommonCameraSettingsStateCameraSettingsChangedBehavior = behavior;
        filter->CmdCommonGPSControllerPositionForRunBehavior = behavior;
        filter->CmdCommonFlightPlanStateAvailabilityStateChangedBehavior = behavior;
        filter->CmdCommonFlightPlanStateComponentStateListChangedBehavior = behavior;
        filter->CmdCommonFlightPlanEventStartingErrorEventBehavior = behavior;
        filter->CmdCommonFlightPlanEventSpeedBridleEventBehavior = behavior;
        filter->CmdCommonARLibsVersionsStateControllerLibARCommandsVersionBehavior = behavior;
        filter->CmdCommonARLibsVersionsStateSkyControllerLibARCommandsVersionBehavior = behavior;
        filter->CmdCommonARLibsVersionsStateDeviceLibARCommandsVersionBehavior = behavior;
    }

    return retError;
}

// Command class Network

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonNetworkBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonNetworkDisconnectBehavior = behavior;
    }

    return retError;
}

// Command class NetworkEvent

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonNetworkEventBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonNetworkEventDisconnectionBehavior = behavior;
    }

    return retError;
}

// Command class Settings

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonSettingsBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonSettingsAllSettingsBehavior = behavior;
        filter->CmdCommonSettingsResetBehavior = behavior;
        filter->CmdCommonSettingsProductNameBehavior = behavior;
        filter->CmdCommonSettingsCountryBehavior = behavior;
        filter->CmdCommonSettingsAutoCountryBehavior = behavior;
    }

    return retError;
}

// Command class SettingsState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonSettingsStateBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonSettingsStateAllSettingsChangedBehavior = behavior;
        filter->CmdCommonSettingsStateResetChangedBehavior = behavior;
        filter->CmdCommonSettingsStateProductNameChangedBehavior = behavior;
        filter->CmdCommonSettingsStateProductVersionChangedBehavior = behavior;
        filter->CmdCommonSettingsStateProductSerialHighChangedBehavior = behavior;
        filter->CmdCommonSettingsStateProductSerialLowChangedBehavior = behavior;
        filter->CmdCommonSettingsStateCountryChangedBehavior = behavior;
        filter->CmdCommonSettingsStateAutoCountryChangedBehavior = behavior;
    }

    return retError;
}

// Command class Common

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCommonBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCommonAllStatesBehavior = behavior;
        filter->CmdCommonCommonCurrentDateBehavior = behavior;
        filter->CmdCommonCommonCurrentTimeBehavior = behavior;
        filter->CmdCommonCommonRebootBehavior = behavior;
    }

    return retError;
}

// Command class CommonState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCommonStateBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCommonStateAllStatesChangedBehavior = behavior;
        filter->CmdCommonCommonStateBatteryStateChangedBehavior = behavior;
        filter->CmdCommonCommonStateMassStorageStateListChangedBehavior = behavior;
        filter->CmdCommonCommonStateMassStorageInfoStateListChangedBehavior = behavior;
        filter->CmdCommonCommonStateCurrentDateChangedBehavior = behavior;
        filter->CmdCommonCommonStateCurrentTimeChangedBehavior = behavior;
        filter->CmdCommonCommonStateMassStorageInfoRemainingListChangedBehavior = behavior;
        filter->CmdCommonCommonStateWifiSignalChangedBehavior = behavior;
        filter->CmdCommonCommonStateSensorsStatesListChangedBehavior = behavior;
    }

    return retError;
}

// Command class OverHeat

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonOverHeatBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonOverHeatSwitchOffBehavior = behavior;
        filter->CmdCommonOverHeatVentilateBehavior = behavior;
    }

    return retError;
}

// Command class OverHeatState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonOverHeatStateBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonOverHeatStateOverHeatChangedBehavior = behavior;
        filter->CmdCommonOverHeatStateOverHeatRegulationChangedBehavior = behavior;
    }

    return retError;
}

// Command class ControllerState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonControllerStateBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonControllerStateIsPilotingChangedBehavior = behavior;
    }

    return retError;
}

// Command class WifiSettings

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonWifiSettingsBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonWifiSettingsOutdoorSettingBehavior = behavior;
    }

    return retError;
}

// Command class WifiSettingsState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonWifiSettingsStateBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonWifiSettingsStateOutdoorSettingsChangedBehavior = behavior;
    }

    return retError;
}

// Command class Mavlink

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonMavlinkBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonMavlinkStartBehavior = behavior;
        filter->CmdCommonMavlinkPauseBehavior = behavior;
        filter->CmdCommonMavlinkStopBehavior = behavior;
    }

    return retError;
}

// Command class MavlinkState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonMavlinkStateBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonMavlinkStateMavlinkFilePlayingStateChangedBehavior = behavior;
        filter->CmdCommonMavlinkStateMavlinkPlayErrorStateChangedBehavior = behavior;
    }

    return retError;
}

// Command class Calibration

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCalibrationBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCalibrationMagnetoCalibrationBehavior = behavior;
    }

    return retError;
}

// Command class CalibrationState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCalibrationStateBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCalibrationStateMagnetoCalibrationStateChangedBehavior = behavior;
        filter->CmdCommonCalibrationStateMagnetoCalibrationRequiredStateBehavior = behavior;
        filter->CmdCommonCalibrationStateMagnetoCalibrationAxisToCalibrateChangedBehavior = behavior;
        filter->CmdCommonCalibrationStateMagnetoCalibrationStartedChangedBehavior = behavior;
    }

    return retError;
}

// Command class CameraSettingsState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCameraSettingsStateBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCameraSettingsStateCameraSettingsChangedBehavior = behavior;
    }

    return retError;
}

// Command class GPS

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonGPSBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonGPSControllerPositionForRunBehavior = behavior;
    }

    return retError;
}

// Command class FlightPlanState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonFlightPlanStateBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonFlightPlanStateAvailabilityStateChangedBehavior = behavior;
        filter->CmdCommonFlightPlanStateComponentStateListChangedBehavior = behavior;
    }

    return retError;
}

// Command class FlightPlanEvent

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonFlightPlanEventBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonFlightPlanEventStartingErrorEventBehavior = behavior;
        filter->CmdCommonFlightPlanEventSpeedBridleEventBehavior = behavior;
    }

    return retError;
}

// Command class ARLibsVersionsState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonARLibsVersionsStateBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;

    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonARLibsVersionsStateControllerLibARCommandsVersionBehavior = behavior;
        filter->CmdCommonARLibsVersionsStateSkyControllerLibARCommandsVersionBehavior = behavior;
        filter->CmdCommonARLibsVersionsStateDeviceLibARCommandsVersionBehavior = behavior;
    }

    return retError;
}

// Command class Network

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonNetworkDisconnectBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonNetworkDisconnectBehavior = behavior;
    }

    return retError;
}


// Command class NetworkEvent

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonNetworkEventDisconnectionBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonNetworkEventDisconnectionBehavior = behavior;
    }

    return retError;
}


// Command class Settings

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonSettingsAllSettingsBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonSettingsAllSettingsBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonSettingsResetBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonSettingsResetBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonSettingsProductNameBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonSettingsProductNameBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonSettingsCountryBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonSettingsCountryBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonSettingsAutoCountryBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonSettingsAutoCountryBehavior = behavior;
    }

    return retError;
}


// Command class SettingsState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonSettingsStateAllSettingsChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonSettingsStateAllSettingsChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonSettingsStateResetChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonSettingsStateResetChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonSettingsStateProductNameChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonSettingsStateProductNameChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonSettingsStateProductVersionChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonSettingsStateProductVersionChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonSettingsStateProductSerialHighChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonSettingsStateProductSerialHighChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonSettingsStateProductSerialLowChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonSettingsStateProductSerialLowChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonSettingsStateCountryChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonSettingsStateCountryChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonSettingsStateAutoCountryChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonSettingsStateAutoCountryChangedBehavior = behavior;
    }

    return retError;
}


// Command class Common

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCommonAllStatesBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCommonAllStatesBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCommonCurrentDateBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCommonCurrentDateBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCommonCurrentTimeBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCommonCurrentTimeBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCommonRebootBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCommonRebootBehavior = behavior;
    }

    return retError;
}


// Command class CommonState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCommonStateAllStatesChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCommonStateAllStatesChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCommonStateBatteryStateChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCommonStateBatteryStateChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCommonStateMassStorageStateListChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCommonStateMassStorageStateListChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCommonStateMassStorageInfoStateListChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCommonStateMassStorageInfoStateListChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCommonStateCurrentDateChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCommonStateCurrentDateChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCommonStateCurrentTimeChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCommonStateCurrentTimeChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCommonStateMassStorageInfoRemainingListChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCommonStateMassStorageInfoRemainingListChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCommonStateWifiSignalChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCommonStateWifiSignalChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCommonStateSensorsStatesListChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCommonStateSensorsStatesListChangedBehavior = behavior;
    }

    return retError;
}


// Command class OverHeat

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonOverHeatSwitchOffBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonOverHeatSwitchOffBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonOverHeatVentilateBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonOverHeatVentilateBehavior = behavior;
    }

    return retError;
}


// Command class OverHeatState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonOverHeatStateOverHeatChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonOverHeatStateOverHeatChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonOverHeatStateOverHeatRegulationChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonOverHeatStateOverHeatRegulationChangedBehavior = behavior;
    }

    return retError;
}


// Command class ControllerState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonControllerStateIsPilotingChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonControllerStateIsPilotingChangedBehavior = behavior;
    }

    return retError;
}


// Command class WifiSettings

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonWifiSettingsOutdoorSettingBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonWifiSettingsOutdoorSettingBehavior = behavior;
    }

    return retError;
}


// Command class WifiSettingsState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonWifiSettingsStateOutdoorSettingsChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonWifiSettingsStateOutdoorSettingsChangedBehavior = behavior;
    }

    return retError;
}


// Command class Mavlink

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonMavlinkStartBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonMavlinkStartBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonMavlinkPauseBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonMavlinkPauseBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonMavlinkStopBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonMavlinkStopBehavior = behavior;
    }

    return retError;
}


// Command class MavlinkState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonMavlinkStateMavlinkFilePlayingStateChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonMavlinkStateMavlinkFilePlayingStateChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonMavlinkStateMavlinkPlayErrorStateChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonMavlinkStateMavlinkPlayErrorStateChangedBehavior = behavior;
    }

    return retError;
}


// Command class Calibration

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCalibrationMagnetoCalibrationBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCalibrationMagnetoCalibrationBehavior = behavior;
    }

    return retError;
}


// Command class CalibrationState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCalibrationStateMagnetoCalibrationStateChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCalibrationStateMagnetoCalibrationStateChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCalibrationStateMagnetoCalibrationRequiredStateBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCalibrationStateMagnetoCalibrationRequiredStateBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCalibrationStateMagnetoCalibrationAxisToCalibrateChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCalibrationStateMagnetoCalibrationAxisToCalibrateChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCalibrationStateMagnetoCalibrationStartedChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCalibrationStateMagnetoCalibrationStartedChangedBehavior = behavior;
    }

    return retError;
}


// Command class CameraSettingsState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonCameraSettingsStateCameraSettingsChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonCameraSettingsStateCameraSettingsChangedBehavior = behavior;
    }

    return retError;
}


// Command class GPS

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonGPSControllerPositionForRunBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonGPSControllerPositionForRunBehavior = behavior;
    }

    return retError;
}


// Command class FlightPlanState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonFlightPlanStateAvailabilityStateChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonFlightPlanStateAvailabilityStateChangedBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonFlightPlanStateComponentStateListChangedBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonFlightPlanStateComponentStateListChangedBehavior = behavior;
    }

    return retError;
}


// Command class FlightPlanEvent

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonFlightPlanEventStartingErrorEventBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonFlightPlanEventStartingErrorEventBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonFlightPlanEventSpeedBridleEventBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonFlightPlanEventSpeedBridleEventBehavior = behavior;
    }

    return retError;
}


// Command class ARLibsVersionsState

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonARLibsVersionsStateControllerLibARCommandsVersionBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonARLibsVersionsStateControllerLibARCommandsVersionBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonARLibsVersionsStateSkyControllerLibARCommandsVersionBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonARLibsVersionsStateSkyControllerLibARCommandsVersionBehavior = behavior;
    }

    return retError;
}

eARCOMMANDS_FILTER_ERROR ARCOMMANDS_Filter_SetCommonARLibsVersionsStateDeviceLibARCommandsVersionBehavior (ARCOMMANDS_Filter_t *filter, eARCOMMANDS_FILTER_STATUS behavior)
{
    eARCOMMANDS_FILTER_ERROR retError = ARCOMMANDS_FILTER_OK;
    if (filter == NULL)
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_FILTER;
    } // No else : Args check

    if ((behavior != ARCOMMANDS_FILTER_STATUS_ALLOWED) &&
        (behavior != ARCOMMANDS_FILTER_STATUS_BLOCKED))
    {
        retError = ARCOMMANDS_FILTER_ERROR_BAD_STATUS;
    } // No else : Arg check

    if (retError == ARCOMMANDS_FILTER_OK)
    {
        filter->CmdCommonARLibsVersionsStateDeviceLibARCommandsVersionBehavior = behavior;
    }

    return retError;
}



// END GENERATED CODE
